/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tic_tac_toe;

import java.awt.Color;
import javax.swing.JOptionPane;




/**
 *
 * @author svv
 */
public class TTT extends javax.swing.JFrame {

    /**
     * Creates new form TTT
     */
   
    User_Change o1=new User_Change();
    public TTT() {
        initComponents();
        t1.setEnabled(false);
        t2.setEnabled(false);
        t3.setEnabled(false);
        t4.setEnabled(false);
        t5.setEnabled(false);
        t6.setEnabled(false);
        t7.setEnabled(false);
        t8.setEnabled(false);
        t9.setEnabled(false);
        jLabel5.setText(""+o1.u21);
        jLabel6.setText(""+o1.u11);
        jLabel5.setBackground(Color.blue);
        jLabel6.setBackground(Color.blue);
        u1.setEnabled(false);
        u2.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        t2 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        t3 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        t4 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        t6 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        t5 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        t7 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        t9 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        t8 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        u2 = new javax.swing.JRadioButton();
        u1 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setTitle("Tic Tac Toe");
        setResizable(false);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t1.setEditable(false);
        t1.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t2.setEditable(false);
        t2.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput1(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t2, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t3.setEditable(false);
        t3.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput2(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t3, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t4.setEditable(false);
        t4.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput3(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t4, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t4, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t6.setEditable(false);
        t6.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput5(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t6, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t6, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t5.setEditable(false);
        t5.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput4(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t5, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t5, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t7.setEditable(false);
        t7.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput6(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t7, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t7)
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t9.setEditable(false);
        t9.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput8(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t9, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t9, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(0, 0, 0)));

        t8.setEditable(false);
        t8.setFont(new java.awt.Font("Tahoma", 1, 80)); // NOI18N
        t8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                XOinput7(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t8, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(t8, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 255));
        jPanel2.setBorder(new javax.swing.border.MatteBorder(null));

        u2.setBackground(new java.awt.Color(102, 102, 255));
        buttonGroup1.add(u2);
        u2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        u2.setForeground(new java.awt.Color(255, 153, 102));

        u1.setBackground(new java.awt.Color(102, 102, 255));
        buttonGroup1.add(u1);
        u1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        u1.setForeground(new java.awt.Color(255, 153, 102));
        u1.setSelected(true);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setOpaque(true);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setOpaque(true);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(u1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(u2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(u1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(u2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(154, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    User_Change o11=new User_Change();
    String user2=o11.us1;
    String user1=o11.us2;
    int ft1=0,ft2=0,ft3=0,ft4=0,ft5=0,ft6=0,ft7=0,ft8=0,ft9=0;
    int n=0;
    String tf1;
    String tf2;
    String tf3;
    String tf4;
    String tf5;
    String tf6;
    String tf7;
    String tf8;
    String tf9;
    public void Restart()
    {
        u1.setSelected(true);
        n=0;
        t1.setText("");
        t2.setText("");
        t3.setText("");
        t4.setText("");
        t5.setText("");
        t6.setText("");
        t7.setText("");
        t8.setText("");
        t9.setText("");
        ft1=0;
        ft2=0;
        ft3=0;
        ft4=0;
        ft5=0;
        ft6=0;
        ft7=0;
        ft8=0;
        ft9=0;
    }
    public void Check()
    {
        tf1=t1.getText();
        tf2=t2.getText();
        tf3=t3.getText();
        tf4=t4.getText();
        tf5=t5.getText();
        tf6=t6.getText();
        tf7=t7.getText();
        tf8=t8.getText();
        tf9=t9.getText();
        if(tf1.equals(user2) && tf2.equals(user2) && tf3.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf1.equals(user1) && tf2.equals(user1) && tf3.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf1.equals(user2) && tf4.equals(user2) && tf7.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf1.equals(user1) && tf4.equals(user1) && tf7.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf1.equals(user2) && tf5.equals(user2) && tf9.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf1.equals(user1) && tf5.equals(user1) && tf9.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf3.equals(user2) && tf5.equals(user2) && tf7.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf3.equals(user1) && tf5.equals(user1) && tf7.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf2.equals(user2) && tf5.equals(user2) && tf8.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf2.equals(user1) && tf5.equals(user1) && tf8.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf3.equals(user2) && tf6.equals(user2) && tf9.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf3.equals(user1) && tf6.equals(user1) && tf9.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf4.equals(user2) && tf5.equals(user2) && tf6.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf4.equals(user1) && tf5.equals(user1) && tf6.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         if(tf7.equals(user2) && tf8.equals(user2) && tf9.equals(user2))
            {
               JOptionPane.showMessageDialog(this, o1.u11+" wins!");
               Restart();
            }
         if(tf7.equals(user1) && tf8.equals(user1) && tf9.equals(user1))
            {
               JOptionPane.showMessageDialog(this, o1.u21+" wins!");
               Restart();
            }
         else
         {
             if(n==9)
             {
                 JOptionPane.showMessageDialog(this, "Draw!");
                 Restart();
             }
         }
    }
    public void User()
    {
        n++;
    }
    public void swap()
    {
        if(n==1)
        {
            u2.setSelected(true);
        }
        if(n==2)
        {
            u1.setSelected(true);
        }
        if(n==3)
        {
            u2.setSelected(true);
        }
        if(n==4)
        {
            u1.setSelected(true);
        }
        if(n==5)
        {
            u2.setSelected(true);
        }
        if(n==6)
        {
            u1.setSelected(true);
        }
        if(n==7)
        {
            u2.setSelected(true);
        }
        if(n==8)
        {
            u1.setSelected(true);
        }
    }
    
    private void XOinput(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput
        if(ft1==0){
        if (u1.isSelected()){
            t1.setText(user2);
        }
         if (u2.isSelected()){
            t1.setText(user1);
        }
         User();
         swap();
         Check();
        }
         ft1++;
    }//GEN-LAST:event_XOinput

    private void XOinput1(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput1
        // TODO add your handling code here:
        if(ft2==0){
        if (u1.isSelected()){
            t2.setText(user2);
        }
         if (u2.isSelected()){
            t2.setText(user1);
        }
         User();
         swap();
         Check();
        }
         ft2++;
    }//GEN-LAST:event_XOinput1

    private void XOinput2(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput2
        // TODO add your handling code here:
        if(ft3==0)
        {
        if (u1.isSelected()){
            t3.setText(user2);
        }
         if (u2.isSelected()){
            t3.setText(user1);
        }
        User();
        swap();
        Check();
        }
        ft3++;
    }//GEN-LAST:event_XOinput2

    private void XOinput3(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput3
        // TODO add your handling code here:
        if(ft4==0){
        if (u1.isSelected()){
            t4.setText(user2);
        }
         if (u2.isSelected()){
            t4.setText(user1);
        }
         User();
         swap();
         Check();
        }
         ft4++;
    }//GEN-LAST:event_XOinput3

    private void XOinput4(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput4
        // TODO add your handling code here:
        if(ft5==0){
        if (u1.isSelected()){
            t5.setText(user2);
        }
         if (u2.isSelected()){
            t5.setText(user1);
        }
         User();
         swap();
         Check();
        }
         ft5++;
    }//GEN-LAST:event_XOinput4

    private void XOinput5(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput5
        if(ft6==0){
        if (u1.isSelected()){
            t6.setText(user2);
        }
         if (u2.isSelected()){
            t6.setText(user1);
        }
        User();
        swap();
        Check();
        }
        ft6++;
    }//GEN-LAST:event_XOinput5

    private void XOinput6(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput6
       if(ft7==0){
        if (u1.isSelected()){
            t7.setText(user2);
        }
         if (u2.isSelected()){
            t7.setText(user1);
        }
        User();
        swap();
        Check();
       }
        ft7++;
    }//GEN-LAST:event_XOinput6

    private void XOinput7(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput7
       if(ft8==0){
        if (u1.isSelected()){
            t8.setText(user2);
        }
         if (u2.isSelected()){
            t8.setText(user1);
        }
        User();
        swap();
        Check();
       }
        ft8++;
    }//GEN-LAST:event_XOinput7

    private void XOinput8(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_XOinput8
       if(ft9==0){
        if (u1.isSelected()){
            t9.setText(user2);
        }
         if (u2.isSelected()){
            t9.setText(user1);
        }
        User();
        swap();
        Check();
       }
        ft9++;
    }//GEN-LAST:event_XOinput8

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        // TODO add your handling code here:
        Pause obj3=new Pause();
        obj3.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_formKeyPressed
   /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TTT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new TTT().setVisible(true);
                
            }
        });
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTextField t9;
    private javax.swing.JRadioButton u1;
    private javax.swing.JRadioButton u2;
    // End of variables declaration//GEN-END:variables
}
