/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tic_tac_toe;

import javax.swing.JOptionPane;

/**
 *
 * @author student
 */
public class User_Change extends javax.swing.JFrame {

    /**
     * Creates new form User_Change
     */
    public User_Change() {
        initComponents();
        jLabel6.setVisible(true);
        jLabel7.setVisible(false);
        tf1.setVisible(true);
        tf2.setVisible(false);
        user1x.setVisible(true);
        user1o.setVisible(true);
        user2x.setVisible(false);
        user2o.setVisible(false);
        stb.setEnabled(false);
    }
    public static String u11;
    public static String u21;
    public static String v;
    public static String v1;
    public static String us1;
    public static String us2;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel41 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tf2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        stb = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        user1x = new javax.swing.JRadioButton();
        user1o = new javax.swing.JRadioButton();
        user2x = new javax.swing.JRadioButton();
        user2o = new javax.swing.JRadioButton();

        setTitle("Selection");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("O");
        getContentPane().add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 40, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Enter Name:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 43, 108, -1));

        tf1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 40, 105, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel7.setText("USER 2");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 0, 90, -1));

        tf2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 40, 105, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, -1, -1));

        stb.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        stb.setText("Start!");
        stb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stbActionPerformed(evt);
            }
        });
        getContentPane().add(stb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("USER 1");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 0, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("X");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 40, -1));

        buttonGroup1.add(user1x);
        user1x.setSelected(true);
        getContentPane().add(user1x, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        buttonGroup1.add(user1o);
        getContentPane().add(user1o, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        buttonGroup2.add(user2x);
        user2x.setSelected(true);
        getContentPane().add(user2x, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        buttonGroup2.add(user2o);
        getContentPane().add(user2o, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jLabel7.setVisible(true);
        jLabel6.setVisible(false);
        tf2.setVisible(true);
        tf1.setVisible(false);
        jButton1.setEnabled(false);
        user2x.setVisible(true);
        user2o.setVisible(true);
        user1x.setVisible(false);
        user1o.setVisible(false);
        user2x.setEnabled(false);
        user2o.setEnabled(false);
        stb.setEnabled(true);
        if(user1x.isSelected()==true)
        {
            us1="X";
            us2="O";
            user2o.setSelected(true);
        }
         if(user1o.isSelected()==true)
        {
            us1="O";
            us2="X";
            user2x.setSelected(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void stbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stbActionPerformed
        // TODO add your handling code here:
        u11=tf1.getText();
        u21=tf2.getText();
        new TTT().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_stbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Change.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new User_Change().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton stb;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JRadioButton user1o;
    private javax.swing.JRadioButton user1x;
    private javax.swing.JRadioButton user2o;
    private javax.swing.JRadioButton user2x;
    // End of variables declaration//GEN-END:variables
}
